# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.targeting_recommendations_api import TargetingRecommendationsApi


class TestTargetingRecommendationsApi(unittest.TestCase):
    """TargetingRecommendationsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = TargetingRecommendationsApi()

    def tearDown(self) -> None:
        pass

    def test_get_target_recommendations(self) -> None:
        """Test case for get_target_recommendations

        Returns a set of recommended products and categories to target
        """
        pass


if __name__ == '__main__':
    unittest.main()
