# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.bid_recommendations_api import BidRecommendationsApi


class TestBidRecommendationsApi(unittest.TestCase):
    """BidRecommendationsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = BidRecommendationsApi()

    def tearDown(self) -> None:
        pass

    def test_get_target_bid_recommendations(self) -> None:
        """Test case for get_target_bid_recommendations

        Returns a set of bid recommendations for targeting clauses
        """
        pass


if __name__ == '__main__':
    unittest.main()
