# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.creative_moderation_policy_violations_inner_violating_video_contents_inner import CreativeModerationPolicyViolationsInnerViolatingVideoContentsInner

class TestCreativeModerationPolicyViolationsInnerViolatingVideoContentsInner(unittest.TestCase):
    """CreativeModerationPolicyViolationsInnerViolatingVideoContentsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreativeModerationPolicyViolationsInnerViolatingVideoContentsInner:
        """Test CreativeModerationPolicyViolationsInnerViolatingVideoContentsInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreativeModerationPolicyViolationsInnerViolatingVideoContentsInner`
        """
        model = CreativeModerationPolicyViolationsInnerViolatingVideoContentsInner()
        if include_optional:
            return CreativeModerationPolicyViolationsInnerViolatingVideoContentsInner(
                reviewed_video_url = '',
                video_evidences = [
                    openapi_client.models.creative_moderation_policy_violations_inner_violating_video_contents_inner_video_evidences_inner.CreativeModeration_policyViolations_inner_violatingVideoContents_inner_videoEvidences_inner(
                        violating_video_position = openapi_client.models.creative_moderation_policy_violations_inner_violating_video_contents_inner_video_evidences_inner_violating_video_position.CreativeModeration_policyViolations_inner_violatingVideoContents_inner_videoEvidences_inner_violatingVideoPosition(
                            start = 56, 
                            end = 56, ), )
                    ]
            )
        else:
            return CreativeModerationPolicyViolationsInnerViolatingVideoContentsInner(
        )
        """

    def testCreativeModerationPolicyViolationsInnerViolatingVideoContentsInner(self):
        """Test CreativeModerationPolicyViolationsInnerViolatingVideoContentsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
