# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.negative_targeting_clause_ex import NegativeTargetingClauseEx

class TestNegativeTargetingClauseEx(unittest.TestCase):
    """NegativeTargetingClauseEx unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> NegativeTargetingClauseEx:
        """Test NegativeTargetingClauseEx
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `NegativeTargetingClauseEx`
        """
        model = NegativeTargetingClauseEx()
        if include_optional:
            return NegativeTargetingClauseEx(
                target_id = 1.337,
                ad_group_id = 1.337,
                state = 'enabled',
                expression_type = 'manual',
                expression = [
                    openapi_client.models.negative_targeting_clause_ex_expression_inner.NegativeTargetingClauseEx_expression_inner(
                        type = 'asinSameAs', 
                        value = 'B0123456789', )
                    ],
                serving_status = 'ADVERTISER_STATUS_ENABLED',
                creation_date = 56,
                last_updated_date = 56
            )
        else:
            return NegativeTargetingClauseEx(
        )
        """

    def testNegativeTargetingClauseEx(self):
        """Test NegativeTargetingClauseEx"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
