# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.targeting_expression_inner import TargetingExpressionInner

class TestTargetingExpressionInner(unittest.TestCase):
    """TargetingExpressionInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TargetingExpressionInner:
        """Test TargetingExpressionInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TargetingExpressionInner`
        """
        model = TargetingExpressionInner()
        if include_optional:
            return TargetingExpressionInner(
                type = 'asinSameAs',
                value = [
                    openapi_client.models.targeting_predicate_base.TargetingPredicateBase(
                        type = 'asinCategorySameAs', )
                    ],
                event_type = 'views'
            )
        else:
            return TargetingExpressionInner(
        )
        """

    def testTargetingExpressionInner(self):
        """Test TargetingExpressionInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
