# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.sd_bid_optimization_v32 import SDBidOptimizationV32

class TestSDBidOptimizationV32(unittest.TestCase):
    """SDBidOptimizationV32 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSDBidOptimizationV32(self):
        """Test SDBidOptimizationV32"""
        # inst = SDBidOptimizationV32()

if __name__ == '__main__':
    unittest.main()
