# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.create_campaign import CreateCampaign

class TestCreateCampaign(unittest.TestCase):
    """CreateCampaign unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateCampaign:
        """Test CreateCampaign
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateCampaign`
        """
        model = CreateCampaign()
        if include_optional:
            return CreateCampaign(
                name = '',
                budget_type = 'daily',
                budget = 3.0,
                start_date = '20190101',
                end_date = '',
                cost_type = 'cpc',
                state = 'enabled',
                portfolio_id = 56,
                tactic = 'T00020'
            )
        else:
            return CreateCampaign(
        )
        """

    def testCreateCampaign(self):
        """Test CreateCampaign"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
