# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.sd_seven_days_missed_opportunities import SDSevenDaysMissedOpportunities

class TestSDSevenDaysMissedOpportunities(unittest.TestCase):
    """SDSevenDaysMissedOpportunities unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SDSevenDaysMissedOpportunities:
        """Test SDSevenDaysMissedOpportunities
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SDSevenDaysMissedOpportunities`
        """
        model = SDSevenDaysMissedOpportunities()
        if include_optional:
            return SDSevenDaysMissedOpportunities(
                start_date = 'Mon May 01 00:00:00 UTC 2023',
                end_date = 'Sun May 07 00:00:00 UTC 2023',
                percent_time_in_budget = 60.5,
                estimated_missed_sales_lower = 200.75,
                estimated_missed_sales_upper = 400.75,
                estimated_missed_clicks_lower = 30,
                estimated_missed_clicks_upper = 50,
                estimated_missed_impressions_lower = 50,
                estimated_missed_impressions_upper = 70,
                estimated_missed_viewable_impressions_lower = 70,
                estimated_missed_viewable_impressions_upper = 90
            )
        else:
            return SDSevenDaysMissedOpportunities(
        )
        """

    def testSDSevenDaysMissedOpportunities(self):
        """Test SDSevenDaysMissedOpportunities"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
