# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.creative_type_in_creative_response import CreativeTypeInCreativeResponse

class TestCreativeTypeInCreativeResponse(unittest.TestCase):
    """CreativeTypeInCreativeResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCreativeTypeInCreativeResponse(self):
        """Test CreativeTypeInCreativeResponse"""
        # inst = CreativeTypeInCreativeResponse()

if __name__ == '__main__':
    unittest.main()
