# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.forecast import Forecast

class TestForecast(unittest.TestCase):
    """Forecast unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Forecast:
        """Test Forecast
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Forecast`
        """
        model = Forecast()
        if include_optional:
            return Forecast(
                metric = 'IMPRESSIONS',
                value = openapi_client.models.forecast_range.ForecastRange(
                    min = 56, 
                    max = 56, )
            )
        else:
            return Forecast(
        )
        """

    def testForecast(self):
        """Test Forecast"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
