# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class LandingPageType(str, Enum):
    """
    The type of the landingPage used. This field is completely optional and will be set in conjunction with the LandingPageUrl to indicate the type of landing page that will be set. This field is not supported when using ASIN or SKU fields.
    """

    """
    allowed enum values
    """
    STORE = 'STORE'
    MOMENT = 'MOMENT'
    OFF_AMAZON_LINK = 'OFF_AMAZON_LINK'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of LandingPageType from a JSON string"""
        return cls(json.loads(json_str))


