# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
from pydantic import BaseModel, ConfigDict, Field, StrictStr, ValidationError, field_validator
from typing import Any, List, Optional
from openapi_client.models.content_targeting_predicate import ContentTargetingPredicate
from openapi_client.models.targeting_predicate import TargetingPredicate
from openapi_client.models.targeting_predicate_legacy import TargetingPredicateLegacy
from openapi_client.models.targeting_predicate_nested import TargetingPredicateNested
from pydantic import StrictStr, Field
from typing import Union, List, Set, Optional, Dict
from typing_extensions import Literal, Self

TARGETINGEXPRESSIONINNER_ONE_OF_SCHEMAS = ["ContentTargetingPredicate", "TargetingPredicate", "TargetingPredicateLegacy", "TargetingPredicateNested"]

class TargetingExpressionInner(BaseModel):
    """
    TargetingExpressionInner
    """
    # data type: TargetingPredicate
    oneof_schema_1_validator: Optional[TargetingPredicate] = None
    # data type: ContentTargetingPredicate
    oneof_schema_2_validator: Optional[ContentTargetingPredicate] = None
    # data type: TargetingPredicateLegacy
    oneof_schema_3_validator: Optional[TargetingPredicateLegacy] = None
    # data type: TargetingPredicateNested
    oneof_schema_4_validator: Optional[TargetingPredicateNested] = None
    actual_instance: Optional[Union[ContentTargetingPredicate, TargetingPredicate, TargetingPredicateLegacy, TargetingPredicateNested]] = None
    one_of_schemas: Set[str] = { "ContentTargetingPredicate", "TargetingPredicate", "TargetingPredicateLegacy", "TargetingPredicateNested" }

    model_config = ConfigDict(
        validate_assignment=True,
        protected_namespaces=(),
    )


    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator('actual_instance')
    def actual_instance_must_validate_oneof(cls, v):
        instance = TargetingExpressionInner.model_construct()
        error_messages = []
        match = 0
        # validate data type: TargetingPredicate
        if not isinstance(v, TargetingPredicate):
            error_messages.append(f"Error! Input type `{type(v)}` is not `TargetingPredicate`")
        else:
            match += 1
        # validate data type: ContentTargetingPredicate
        if not isinstance(v, ContentTargetingPredicate):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ContentTargetingPredicate`")
        else:
            match += 1
        # validate data type: TargetingPredicateLegacy
        if not isinstance(v, TargetingPredicateLegacy):
            error_messages.append(f"Error! Input type `{type(v)}` is not `TargetingPredicateLegacy`")
        else:
            match += 1
        # validate data type: TargetingPredicateNested
        if not isinstance(v, TargetingPredicateNested):
            error_messages.append(f"Error! Input type `{type(v)}` is not `TargetingPredicateNested`")
        else:
            match += 1
        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when setting `actual_instance` in TargetingExpressionInner with oneOf schemas: ContentTargetingPredicate, TargetingPredicate, TargetingPredicateLegacy, TargetingPredicateNested. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when setting `actual_instance` in TargetingExpressionInner with oneOf schemas: ContentTargetingPredicate, TargetingPredicate, TargetingPredicateLegacy, TargetingPredicateNested. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: Union[str, Dict[str, Any]]) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        error_messages = []
        match = 0

        # deserialize data into TargetingPredicate
        try:
            instance.actual_instance = TargetingPredicate.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into ContentTargetingPredicate
        try:
            instance.actual_instance = ContentTargetingPredicate.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into TargetingPredicateLegacy
        try:
            instance.actual_instance = TargetingPredicateLegacy.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into TargetingPredicateNested
        try:
            instance.actual_instance = TargetingPredicateNested.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))

        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when deserializing the JSON string into TargetingExpressionInner with oneOf schemas: ContentTargetingPredicate, TargetingPredicate, TargetingPredicateLegacy, TargetingPredicateNested. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when deserializing the JSON string into TargetingExpressionInner with oneOf schemas: ContentTargetingPredicate, TargetingPredicate, TargetingPredicateLegacy, TargetingPredicateNested. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        if hasattr(self.actual_instance, "to_json") and callable(self.actual_instance.to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> Optional[Union[Dict[str, Any], ContentTargetingPredicate, TargetingPredicate, TargetingPredicateLegacy, TargetingPredicateNested]]:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        if hasattr(self.actual_instance, "to_dict") and callable(self.actual_instance.to_dict):
            return self.actual_instance.to_dict()
        else:
            # primitive type
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())


