# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.sd_forecast_request_targeting_clause import SDForecastRequestTargetingClause

class TestSDForecastRequestTargetingClause(unittest.TestCase):
    """SDForecastRequestTargetingClause unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SDForecastRequestTargetingClause:
        """Test SDForecastRequestTargetingClause
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SDForecastRequestTargetingClause`
        """
        model = SDForecastRequestTargetingClause()
        if include_optional:
            return SDForecastRequestTargetingClause(
                state = 'enabled',
                bid = 0.02,
                target_id = 56,
                ad_group_id = 56,
                expression_type = 'manual',
                expression = [
                    null
                    ],
                resolved_expression = [
                    null
                    ]
            )
        else:
            return SDForecastRequestTargetingClause(
        )
        """

    def testSDForecastRequestTargetingClause(self):
        """Test SDForecastRequestTargetingClause"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
