# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.forecasts_api import ForecastsApi


class TestForecastsApi(unittest.TestCase):
    """ForecastsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ForecastsApi()

    def tearDown(self) -> None:
        pass

    def test_create_sd_forecast(self) -> None:
        """Test case for create_sd_forecast

        Return forecasts for an ad group that may or may not exist.
        """
        pass


if __name__ == '__main__':
    unittest.main()
