# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.sd_product_targeting_recommendations_success import SDProductTargetingRecommendationsSuccess

class TestSDProductTargetingRecommendationsSuccess(unittest.TestCase):
    """SDProductTargetingRecommendationsSuccess unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SDProductTargetingRecommendationsSuccess:
        """Test SDProductTargetingRecommendationsSuccess
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SDProductTargetingRecommendationsSuccess`
        """
        model = SDProductTargetingRecommendationsSuccess()
        if include_optional:
            return SDProductTargetingRecommendationsSuccess(
                code = '200',
                name = '',
                recommendations = [
                    openapi_client.models.sd_product_recommendation_v32.SDProductRecommendationV32(
                        asin = 'B00PN11UNW', 
                        rank = 1, 
                        advertised_asins = [
                            'B00PN11UNW'
                            ], )
                    ]
            )
        else:
            return SDProductTargetingRecommendationsSuccess(
        )
        """

    def testSDProductTargetingRecommendationsSuccess(self):
        """Test SDProductTargetingRecommendationsSuccess"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
