# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.curve import Curve

class TestCurve(unittest.TestCase):
    """Curve unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Curve:
        """Test Curve
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Curve`
        """
        model = Curve()
        if include_optional:
            return Curve(
                meet_threshold = True,
                graph = 'BUDGET',
                points = [
                    openapi_client.models.curve_point.CurvePoint(
                        is_focus = True, 
                        x = [
                            openapi_client.models.curve_point_fixed_value.CurvePointFixedValue(
                                value = null, )
                            ], 
                        y = [
                            openapi_client.models.curve_point_ranged_value.CurvePointRangedValue(
                                label = 'CLICKS', 
                                value = openapi_client.models.forecast_range_double.ForecastRangeDouble(
                                    min = null, 
                                    mean = null, 
                                    max = null, ), )
                            ], )
                    ]
            )
        else:
            return Curve(
        )
        """

    def testCurve(self):
        """Test Curve"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
