# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.brand_safety_request_status import BrandSafetyRequestStatus

class TestBrandSafetyRequestStatus(unittest.TestCase):
    """BrandSafetyRequestStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BrandSafetyRequestStatus:
        """Test BrandSafetyRequestStatus
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BrandSafetyRequestStatus`
        """
        model = BrandSafetyRequestStatus()
        if include_optional:
            return BrandSafetyRequestStatus(
                request_id = '',
                timestamp = '',
                status = 'IN_PROGRESS',
                status_details = ''
            )
        else:
            return BrandSafetyRequestStatus(
        )
        """

    def testBrandSafetyRequestStatus(self):
        """Test BrandSafetyRequestStatus"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
