# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.base_targeting_clause import BaseTargetingClause

class TestBaseTargetingClause(unittest.TestCase):
    """BaseTargetingClause unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BaseTargetingClause:
        """Test BaseTargetingClause
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BaseTargetingClause`
        """
        model = BaseTargetingClause()
        if include_optional:
            return BaseTargetingClause(
                state = 'enabled',
                bid = 0.02
            )
        else:
            return BaseTargetingClause(
        )
        """

    def testBaseTargetingClause(self):
        """Test BaseTargetingClause"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
