# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.brand_safety_get_response import BrandSafetyGetResponse

class TestBrandSafetyGetResponse(unittest.TestCase):
    """BrandSafetyGetResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BrandSafetyGetResponse:
        """Test BrandSafetyGetResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BrandSafetyGetResponse`
        """
        model = BrandSafetyGetResponse()
        if include_optional:
            return BrandSafetyGetResponse(
                pagination = openapi_client.models.brand_safety_get_response_pagination.BrandSafetyGetResponsePagination(
                    total = 56, 
                    limit = 56, 
                    offset = 56, ),
                domains = [
                    openapi_client.models.brand_safety_deny_list_processed_domain.BrandSafetyDenyListProcessedDomain(
                        domain_id = 56, 
                        name = '', 
                        type = 'WEBSITE', 
                        state = 'ENABLED', 
                        created_at = '2018-09-16T11:43:21Z', 
                        last_modified = '2018-09-16T11:43:21Z', )
                    ]
            )
        else:
            return BrandSafetyGetResponse(
        )
        """

    def testBrandSafetyGetResponse(self):
        """Test BrandSafetyGetResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
