# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.sd_targeting_bid_recommendations_request_v31 import SDTargetingBidRecommendationsRequestV31

class TestSDTargetingBidRecommendationsRequestV31(unittest.TestCase):
    """SDTargetingBidRecommendationsRequestV31 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SDTargetingBidRecommendationsRequestV31:
        """Test SDTargetingBidRecommendationsRequestV31
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SDTargetingBidRecommendationsRequestV31`
        """
        model = SDTargetingBidRecommendationsRequestV31()
        if include_optional:
            return SDTargetingBidRecommendationsRequestV31(
                products = [
                    openapi_client.models.sd_goal_product.SDGoalProduct(
                        asin = 'B00PN11UNW', )
                    ],
                targeting_clauses = [
                    openapi_client.models.sd_targeting_bid_recommendations_request_v33_targeting_clauses_inner.SDTargetingBidRecommendationsRequestV33_targetingClauses_inner(
                        targeting_clause = openapi_client.models.sd_targeting_clause_v31.SDTargetingClauseV31(
                            expression_type = 'manual', 
                            expression = [
                                null
                                ], ), )
                    ]
            )
        else:
            return SDTargetingBidRecommendationsRequestV31(
                targeting_clauses = [
                    openapi_client.models.sd_targeting_bid_recommendations_request_v33_targeting_clauses_inner.SDTargetingBidRecommendationsRequestV33_targetingClauses_inner(
                        targeting_clause = openapi_client.models.sd_targeting_clause_v31.SDTargetingClauseV31(
                            expression_type = 'manual', 
                            expression = [
                                null
                                ], ), )
                    ],
        )
        """

    def testSDTargetingBidRecommendationsRequestV31(self):
        """Test SDTargetingBidRecommendationsRequestV31"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
