# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.sd_target_expression_v31 import SDTargetExpressionV31

class TestSDTargetExpressionV31(unittest.TestCase):
    """SDTargetExpressionV31 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SDTargetExpressionV31:
        """Test SDTargetExpressionV31
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SDTargetExpressionV31`
        """
        model = SDTargetExpressionV31()
        if include_optional:
            return SDTargetExpressionV31(
                type = 'asinSameAs',
                value = [
                    openapi_client.models.sd_targeting_predicate_base_v31.SDTargetingPredicateBaseV31(
                        type = 'asinCategorySameAs', )
                    ]
            )
        else:
            return SDTargetExpressionV31(
                type = 'asinSameAs',
                value = [
                    openapi_client.models.sd_targeting_predicate_base_v31.SDTargetingPredicateBaseV31(
                        type = 'asinCategorySameAs', )
                    ],
        )
        """

    def testSDTargetExpressionV31(self):
        """Test SDTargetExpressionV31"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
