# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.negative_targeting_api import NegativeTargetingApi


class TestNegativeTargetingApi(unittest.TestCase):
    """NegativeTargetingApi unit test stubs"""

    def setUp(self) -> None:
        self.api = NegativeTargetingApi()

    def tearDown(self) -> None:
        pass

    def test_archive_negative_targeting_clause(self) -> None:
        """Test case for archive_negative_targeting_clause

        Sets the `state` of a negative targeting clause to `archived`.
        """
        pass

    def test_create_negative_targeting_clauses(self) -> None:
        """Test case for create_negative_targeting_clauses

        Creates one or more negative targeting clauses.
        """
        pass

    def test_get_negative_targets(self) -> None:
        """Test case for get_negative_targets

        Gets a negative targeting clause specified by identifier.
        """
        pass

    def test_get_negative_targets_ex(self) -> None:
        """Test case for get_negative_targets_ex

        Gets extended information for a negative targeting clause.
        """
        pass

    def test_list_negative_targeting_clauses(self) -> None:
        """Test case for list_negative_targeting_clauses

        Gets a list of negative targeting clauses.
        """
        pass

    def test_list_negative_targeting_clauses_ex(self) -> None:
        """Test case for list_negative_targeting_clauses_ex

        Gets a list of negative targeting clause objects with extended fields.
        """
        pass

    def test_update_negative_targeting_clauses(self) -> None:
        """Test case for update_negative_targeting_clauses

        Updates one or more negative targeting clauses.
        """
        pass


if __name__ == '__main__':
    unittest.main()
