# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.ad_groups_api import AdGroupsApi


class TestAdGroupsApi(unittest.TestCase):
    """AdGroupsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AdGroupsApi()

    def tearDown(self) -> None:
        pass

    def test_archive_ad_group(self) -> None:
        """Test case for archive_ad_group

        Sets the ad group status to archived.
        """
        pass

    def test_create_ad_groups(self) -> None:
        """Test case for create_ad_groups

        Creates one or more ad groups.
        """
        pass

    def test_get_ad_group(self) -> None:
        """Test case for get_ad_group

        Gets a requested ad group.
        """
        pass

    def test_get_ad_group_response_ex(self) -> None:
        """Test case for get_ad_group_response_ex

        Gets extended information for a requested ad group.
        """
        pass

    def test_list_ad_groups(self) -> None:
        """Test case for list_ad_groups

        Gets a list of ad groups.
        """
        pass

    def test_list_ad_groups_ex(self) -> None:
        """Test case for list_ad_groups_ex

        Gets a list of ad groups with extended fields.
        """
        pass

    def test_update_ad_groups(self) -> None:
        """Test case for update_ad_groups

        Updates on or more ad groups.
        """
        pass


if __name__ == '__main__':
    unittest.main()
