# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.create_budget_rules_response import CreateBudgetRulesResponse

class TestCreateBudgetRulesResponse(unittest.TestCase):
    """CreateBudgetRulesResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateBudgetRulesResponse:
        """Test CreateBudgetRulesResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateBudgetRulesResponse`
        """
        model = CreateBudgetRulesResponse()
        if include_optional:
            return CreateBudgetRulesResponse(
                responses = [
                    openapi_client.models.budget_rule_response.BudgetRuleResponse(
                        code = '', 
                        details = '', 
                        rule_id = '', 
                        associated_campaign_ids = [
                            ''
                            ], )
                    ]
            )
        else:
            return CreateBudgetRulesResponse(
        )
        """

    def testCreateBudgetRulesResponse(self):
        """Test CreateBudgetRulesResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
