# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.creative_moderation_policy_violations_inner_violating_headline_contents_inner_text_evidence_inner_violating_text_position import CreativeModerationPolicyViolationsInnerViolatingHeadlineContentsInnerTextEvidenceInnerViolatingTextPosition

class TestCreativeModerationPolicyViolationsInnerViolatingHeadlineContentsInnerTextEvidenceInnerViolatingTextPosition(unittest.TestCase):
    """CreativeModerationPolicyViolationsInnerViolatingHeadlineContentsInnerTextEvidenceInnerViolatingTextPosition unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreativeModerationPolicyViolationsInnerViolatingHeadlineContentsInnerTextEvidenceInnerViolatingTextPosition:
        """Test CreativeModerationPolicyViolationsInnerViolatingHeadlineContentsInnerTextEvidenceInnerViolatingTextPosition
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreativeModerationPolicyViolationsInnerViolatingHeadlineContentsInnerTextEvidenceInnerViolatingTextPosition`
        """
        model = CreativeModerationPolicyViolationsInnerViolatingHeadlineContentsInnerTextEvidenceInnerViolatingTextPosition()
        if include_optional:
            return CreativeModerationPolicyViolationsInnerViolatingHeadlineContentsInnerTextEvidenceInnerViolatingTextPosition(
                start = 56,
                end = 56
            )
        else:
            return CreativeModerationPolicyViolationsInnerViolatingHeadlineContentsInnerTextEvidenceInnerViolatingTextPosition(
        )
        """

    def testCreativeModerationPolicyViolationsInnerViolatingHeadlineContentsInnerTextEvidenceInnerViolatingTextPosition(self):
        """Test CreativeModerationPolicyViolationsInnerViolatingHeadlineContentsInnerTextEvidenceInnerViolatingTextPosition"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
