# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.ad_group_response_ex import AdGroupResponseEx

class TestAdGroupResponseEx(unittest.TestCase):
    """AdGroupResponseEx unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AdGroupResponseEx:
        """Test AdGroupResponseEx
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AdGroupResponseEx`
        """
        model = AdGroupResponseEx()
        if include_optional:
            return AdGroupResponseEx(
                ad_group_id = 1.337,
                name = '',
                campaign_id = 1.337,
                default_bid = 1.337,
                state = 'enabled',
                tactic = 'T00020',
                creative_type = 'IMAGE',
                serving_status = 'ADVERTISER_STATUS_ENABLED',
                bid_optimization = 'reach',
                creation_date = 56,
                last_updated_date = 56
            )
        else:
            return AdGroupResponseEx(
        )
        """

    def testAdGroupResponseEx(self):
        """Test AdGroupResponseEx"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
