# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.sd_theme_recommendations_v34_themes import SDThemeRecommendationsV34Themes

class TestSDThemeRecommendationsV34Themes(unittest.TestCase):
    """SDThemeRecommendationsV34Themes unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SDThemeRecommendationsV34Themes:
        """Test SDThemeRecommendationsV34Themes
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SDThemeRecommendationsV34Themes`
        """
        model = SDThemeRecommendationsV34Themes()
        if include_optional:
            return SDThemeRecommendationsV34Themes(
                products = [
                    null
                    ]
            )
        else:
            return SDThemeRecommendationsV34Themes(
        )
        """

    def testSDThemeRecommendationsV34Themes(self):
        """Test SDThemeRecommendationsV34Themes"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
