# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.sd_targeting_recommendations_response_v35 import SDTargetingRecommendationsResponseV35

class TestSDTargetingRecommendationsResponseV35(unittest.TestCase):
    """SDTargetingRecommendationsResponseV35 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SDTargetingRecommendationsResponseV35:
        """Test SDTargetingRecommendationsResponseV35
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SDTargetingRecommendationsResponseV35`
        """
        model = SDTargetingRecommendationsResponseV35()
        if include_optional:
            return SDTargetingRecommendationsResponseV35(
                recommendations = openapi_client.models.sd_targeting_recommendations_v35.SDTargetingRecommendationsV35(
                    products = [
                        openapi_client.models.sd_product_recommendations_v32.SDProductRecommendationsV32()
                        ], 
                    categories = [
                        openapi_client.models.sd_category_recommendation_v33.SDCategoryRecommendationV33(
                            category = 7352105011, 
                            name = '', 
                            translated_name = '', 
                            path = [
                                ''
                                ], 
                            translated_path = [
                                ''
                                ], 
                            targetable_asin_count_range = openapi_client.models.sd_category_recommendation_v33_targetable_asin_count_range.SDCategoryRecommendationV33_targetableAsinCountRange(
                                range_lower = 56, 
                                range_upper = 56, ), 
                            rank = 1, )
                        ], 
                    audiences = [
                        openapi_client.models.sd_audience_category_recommendations.SDAudienceCategoryRecommendations()
                        ], 
                    content_categories = [
                        openapi_client.models.sd_content_category_recommendations.SDContentCategoryRecommendations(
                            content_category = 'amzn1.iab-content.647', 
                            name = 'Drama', 
                            rank = 1, )
                        ], 
                    themes = openapi_client.models.sd_theme_recommendations_v34.SDThemeRecommendationsV34(), )
            )
        else:
            return SDTargetingRecommendationsResponseV35(
        )
        """

    def testSDTargetingRecommendationsResponseV35(self):
        """Test SDTargetingRecommendationsResponseV35"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
