# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
from inspect import getfullargspec
import json
import pprint
import re  # noqa: F401
from pydantic import BaseModel, ConfigDict, Field, StrictStr, ValidationError, field_validator
from typing import Optional
from openapi_client.models.background_creative_properties import BackgroundCreativeProperties
from openapi_client.models.custom_image_creative_properties import CustomImageCreativeProperties
from openapi_client.models.headline_creative_properties import HeadlineCreativeProperties
from openapi_client.models.lead_gen_creative_properties import LeadGenCreativeProperties
from openapi_client.models.logo_creative_properties import LogoCreativeProperties
from openapi_client.models.video_creative_properties import VideoCreativeProperties
from typing import Union, Any, List, Set, TYPE_CHECKING, Optional, Dict
from typing_extensions import Literal, Self
from pydantic import Field

CREATIVEPROPERTIES_ANY_OF_SCHEMAS = ["BackgroundCreativeProperties", "CustomImageCreativeProperties", "HeadlineCreativeProperties", "LeadGenCreativeProperties", "LogoCreativeProperties", "VideoCreativeProperties"]

class CreativeProperties(BaseModel):
    """
    Select customizations on your creative from any combination of headline, logo, custom image and backgrounds.
    """

    # data type: HeadlineCreativeProperties
    anyof_schema_1_validator: Optional[HeadlineCreativeProperties] = None
    # data type: LogoCreativeProperties
    anyof_schema_2_validator: Optional[LogoCreativeProperties] = None
    # data type: CustomImageCreativeProperties
    anyof_schema_3_validator: Optional[CustomImageCreativeProperties] = None
    # data type: VideoCreativeProperties
    anyof_schema_4_validator: Optional[VideoCreativeProperties] = None
    # data type: BackgroundCreativeProperties
    anyof_schema_5_validator: Optional[BackgroundCreativeProperties] = None
    # data type: LeadGenCreativeProperties
    anyof_schema_6_validator: Optional[LeadGenCreativeProperties] = None
    if TYPE_CHECKING:
        actual_instance: Optional[Union[BackgroundCreativeProperties, CustomImageCreativeProperties, HeadlineCreativeProperties, LeadGenCreativeProperties, LogoCreativeProperties, VideoCreativeProperties]] = None
    else:
        actual_instance: Any = None
    any_of_schemas: Set[str] = { "BackgroundCreativeProperties", "CustomImageCreativeProperties", "HeadlineCreativeProperties", "LeadGenCreativeProperties", "LogoCreativeProperties", "VideoCreativeProperties" }

    model_config = {
        "validate_assignment": True,
        "protected_namespaces": (),
    }

    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator('actual_instance')
    def actual_instance_must_validate_anyof(cls, v):
        instance = CreativeProperties.model_construct()
        error_messages = []
        # validate data type: HeadlineCreativeProperties
        if not isinstance(v, HeadlineCreativeProperties):
            error_messages.append(f"Error! Input type `{type(v)}` is not `HeadlineCreativeProperties`")
        else:
            return v

        # validate data type: LogoCreativeProperties
        if not isinstance(v, LogoCreativeProperties):
            error_messages.append(f"Error! Input type `{type(v)}` is not `LogoCreativeProperties`")
        else:
            return v

        # validate data type: CustomImageCreativeProperties
        if not isinstance(v, CustomImageCreativeProperties):
            error_messages.append(f"Error! Input type `{type(v)}` is not `CustomImageCreativeProperties`")
        else:
            return v

        # validate data type: VideoCreativeProperties
        if not isinstance(v, VideoCreativeProperties):
            error_messages.append(f"Error! Input type `{type(v)}` is not `VideoCreativeProperties`")
        else:
            return v

        # validate data type: BackgroundCreativeProperties
        if not isinstance(v, BackgroundCreativeProperties):
            error_messages.append(f"Error! Input type `{type(v)}` is not `BackgroundCreativeProperties`")
        else:
            return v

        # validate data type: LeadGenCreativeProperties
        if not isinstance(v, LeadGenCreativeProperties):
            error_messages.append(f"Error! Input type `{type(v)}` is not `LeadGenCreativeProperties`")
        else:
            return v

        if error_messages:
            # no match
            raise ValueError("No match found when setting the actual_instance in CreativeProperties with anyOf schemas: BackgroundCreativeProperties, CustomImageCreativeProperties, HeadlineCreativeProperties, LeadGenCreativeProperties, LogoCreativeProperties, VideoCreativeProperties. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: Dict[str, Any]) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        error_messages = []
        # anyof_schema_1_validator: Optional[HeadlineCreativeProperties] = None
        try:
            instance.actual_instance = HeadlineCreativeProperties.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))
        # anyof_schema_2_validator: Optional[LogoCreativeProperties] = None
        try:
            instance.actual_instance = LogoCreativeProperties.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))
        # anyof_schema_3_validator: Optional[CustomImageCreativeProperties] = None
        try:
            instance.actual_instance = CustomImageCreativeProperties.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))
        # anyof_schema_4_validator: Optional[VideoCreativeProperties] = None
        try:
            instance.actual_instance = VideoCreativeProperties.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))
        # anyof_schema_5_validator: Optional[BackgroundCreativeProperties] = None
        try:
            instance.actual_instance = BackgroundCreativeProperties.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))
        # anyof_schema_6_validator: Optional[LeadGenCreativeProperties] = None
        try:
            instance.actual_instance = LeadGenCreativeProperties.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))

        if error_messages:
            # no match
            raise ValueError("No match found when deserializing the JSON string into CreativeProperties with anyOf schemas: BackgroundCreativeProperties, CustomImageCreativeProperties, HeadlineCreativeProperties, LeadGenCreativeProperties, LogoCreativeProperties, VideoCreativeProperties. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        if hasattr(self.actual_instance, "to_json") and callable(self.actual_instance.to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> Optional[Union[Dict[str, Any], BackgroundCreativeProperties, CustomImageCreativeProperties, HeadlineCreativeProperties, LeadGenCreativeProperties, LogoCreativeProperties, VideoCreativeProperties]]:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        if hasattr(self.actual_instance, "to_dict") and callable(self.actual_instance.to_dict):
            return self.actual_instance.to_dict()
        else:
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())


