# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Union
from openapi_client.models.creative_moderation_policy_violations_inner import CreativeModerationPolicyViolationsInner
from openapi_client.models.creative_type_in_creative_response import CreativeTypeInCreativeResponse
from typing import Optional, Set
from typing_extensions import Self

class CreativeModeration(BaseModel):
    """
    System generated Creative moderation.
    """ # noqa: E501
    creative_id: Union[StrictFloat, StrictInt] = Field(description="Unique identifier of the creative.", alias="creativeId")
    creative_type: CreativeTypeInCreativeResponse = Field(alias="creativeType")
    moderation_status: StrictStr = Field(description="The moderation status of the creative. |Status|Description| |------|-----------| |APPROVED|Moderation for the creative is complete.| |IN_PROGRESS|Moderation for the creative is in progress. The expected date and time for completion are specfied in the `etaForModeration` field.| |REJECTED|The creative has failed moderation. Specific information about the content that violated policy is available in `policyViolations`.|", alias="moderationStatus")
    eta_for_moderation: datetime = Field(description="Expected date and time by which moderation will be complete.", alias="etaForModeration")
    policy_violations: List[CreativeModerationPolicyViolationsInner] = Field(description="A list of policy violations for a creative that has failed moderation.", alias="policyViolations")
    __properties: ClassVar[List[str]] = ["creativeId", "creativeType", "moderationStatus", "etaForModeration", "policyViolations"]

    @field_validator('moderation_status')
    def moderation_status_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['APPROVED', 'PENDING_REVIEW', 'REJECTED']):
            raise ValueError("must be one of enum values ('APPROVED', 'PENDING_REVIEW', 'REJECTED')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CreativeModeration from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in policy_violations (list)
        _items = []
        if self.policy_violations:
            for _item in self.policy_violations:
                if _item:
                    _items.append(_item.to_dict())
            _dict['policyViolations'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CreativeModeration from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "creativeId": obj.get("creativeId"),
            "creativeType": obj.get("creativeType"),
            "moderationStatus": obj.get("moderationStatus"),
            "etaForModeration": obj.get("etaForModeration"),
            "policyViolations": [CreativeModerationPolicyViolationsInner.from_dict(_item) for _item in obj["policyViolations"]] if obj.get("policyViolations") is not None else None
        })
        return _obj


