# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from openapi_client.models.creative_moderation_policy_violations_inner_violating_brand_logo_contents_inner_image_evidences_inner import CreativeModerationPolicyViolationsInnerViolatingBrandLogoContentsInnerImageEvidencesInner
from typing import Optional, Set
from typing_extensions import Self

class CreativeModerationPolicyViolationsInnerViolatingBrandLogoContentsInner(BaseModel):
    """
    CreativeModerationPolicyViolationsInnerViolatingBrandLogoContentsInner
    """ # noqa: E501
    reviewed_image_url: Optional[StrictStr] = Field(default=None, description="Address of the image reviewed during moderation.", alias="reviewedImageUrl")
    image_evidences: Optional[List[CreativeModerationPolicyViolationsInnerViolatingBrandLogoContentsInnerImageEvidencesInner]] = Field(default=None, alias="imageEvidences")
    __properties: ClassVar[List[str]] = ["reviewedImageUrl", "imageEvidences"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CreativeModerationPolicyViolationsInnerViolatingBrandLogoContentsInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in image_evidences (list)
        _items = []
        if self.image_evidences:
            for _item in self.image_evidences:
                if _item:
                    _items.append(_item.to_dict())
            _dict['imageEvidences'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CreativeModerationPolicyViolationsInnerViolatingBrandLogoContentsInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "reviewedImageUrl": obj.get("reviewedImageUrl"),
            "imageEvidences": [CreativeModerationPolicyViolationsInnerViolatingBrandLogoContentsInnerImageEvidencesInner.from_dict(_item) for _item in obj["imageEvidences"]] if obj.get("imageEvidences") is not None else None
        })
        return _obj


