# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from openapi_client.models.curve_point_fixed_value import CurvePointFixedValue
from openapi_client.models.curve_point_ranged_value import CurvePointRangedValue
from typing import Optional, Set
from typing_extensions import Self

class CurvePoint(BaseModel):
    """
    A single point on a curve.
    """ # noqa: E501
    is_focus: Optional[StrictBool] = Field(default=None, description="If this point is the point with the focus circle.", alias="isFocus")
    x: Optional[List[CurvePointFixedValue]] = Field(default=None, description="x-axis value.")
    y: Optional[Annotated[List[CurvePointRangedValue], Field(min_length=0, max_length=2)]] = Field(default=None, description="y-axis value of multiple KPI types.")
    __properties: ClassVar[List[str]] = ["isFocus", "x", "y"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CurvePoint from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in x (list)
        _items = []
        if self.x:
            for _item in self.x:
                if _item:
                    _items.append(_item.to_dict())
            _dict['x'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in y (list)
        _items = []
        if self.y:
            for _item in self.y:
                if _item:
                    _items.append(_item.to_dict())
            _dict['y'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CurvePoint from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "isFocus": obj.get("isFocus"),
            "x": [CurvePointFixedValue.from_dict(_item) for _item in obj["x"]] if obj.get("x") is not None else None,
            "y": [CurvePointRangedValue.from_dict(_item) for _item in obj["y"]] if obj.get("y") is not None else None
        })
        return _obj


