# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class TacticFilter(str, Enum):
    """
    Optional. Restricts results to entities with the advertising tactic associated with the campaign. Must be one of the following table lists available tactic names: |Tactic Name|Type|Description| |-----------|-----|-----------| |T00020     |Contextual targeting | Choose individual products to show your ads in placements related to those products.<br> Choose individual categories to show your ads in placements related to those categories on and off Amazon.| |T00030     |Audiences or Contextual Targeting | Select individual products, categories, refined categories, or audiences to show your ads.|
    """

    """
    allowed enum values
    """
    T00020 = 'T00020'
    T00030 = 'T00030'
    T00020_COMMA_T00030 = 'T00020,T00030'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of TacticFilter from a JSON string"""
        return cls(json.loads(json_str))


