---
servers:
- url: "http://localhost:8080"
openapi: "3.0.3"
paths:
  /sd/productAds:
    $ref: "./sponsored-display.yaml#/paths/~1sd~1productAds"
  /sd/campaigns/{campaignId}:
    $ref: "./sponsored-display.yaml#/paths/~1sd~1campaigns~1{campaignId}"
  /sd/locations/delete:
    $ref: "./sponsored-display.yaml#/paths/~1sd~1locations~1delete"
  /sd/adGroups/{adGroupId}/optimizationRules:
    $ref: "./sponsored-display.yaml#/paths/~1sd~1adGroups~1{adGroupId}~1optimizationRules"
  /sd/negativeTargets/extended/{negativeTargetId}:
    $ref: "./sponsored-display.yaml#/paths/~1sd~1negativeTargets~1extended~1{negativeTargetId}"
  /sd/adGroups/extended/{adGroupId}:
    $ref: "./sponsored-display.yaml#/paths/~1sd~1adGroups~1extended~1{adGroupId}"
  /sd/productAds/{adId}:
    $ref: "./sponsored-display.yaml#/paths/~1sd~1productAds~1{adId}"
  /sd/locations:
    $ref: "./sponsored-display.yaml#/paths/~1sd~1locations"
  /sd/{recordType}/report:
    $ref: "./sponsored-display.yaml#/paths/~1sd~1{recordType}~1report"
  /sd/moderation/creatives:
    $ref: "./sponsored-display.yaml#/paths/~1sd~1moderation~1creatives"
  /sd/adGroups/{adGroupId}:
    $ref: "./sponsored-display.yaml#/paths/~1sd~1adGroups~1{adGroupId}"
  /sd/adGroups/{adGroupId}/optimizationRules/disassociate:
    $ref: "./sponsored-display.yaml#/paths/~1sd~1adGroups~1{adGroupId}~1optimizationRules~1disassociate"
  /sd/productAds/extended/{adId}:
    $ref: "./sponsored-display.yaml#/paths/~1sd~1productAds~1extended~1{adId}"
  /sd/targets/recommendations:
    $ref: "./sponsored-display.yaml#/paths/~1sd~1targets~1recommendations"
  /sd/recommendations/creative/headline:
    $ref: "./sponsored-display.yaml#/paths/~1sd~1recommendations~1creative~1headline"
  /sd/adGroups:
    $ref: "./sponsored-display.yaml#/paths/~1sd~1adGroups"
  /sd/campaigns/extended:
    $ref: "./sponsored-display.yaml#/paths/~1sd~1campaigns~1extended"
  /v2/profiles:
    $ref: "./profiles.yaml#/paths/~1v2~1profiles"
  /sd/snapshots/{snapshotId}:
    $ref: "./sponsored-display.yaml#/paths/~1sd~1snapshots~1{snapshotId}"
  /sd/optimizationRules/{optimizationRuleId}:
    $ref: "./sponsored-display.yaml#/paths/~1sd~1optimizationRules~1{optimizationRuleId}"
  /sd/brandSafety/{requestId}/results:
    $ref: "./sponsored-display.yaml#/paths/~1sd~1brandSafety~1{requestId}~1results"
  /sd/budgetRules/{budgetRuleId}:
    $ref: "./sponsored-display.yaml#/paths/~1sd~1budgetRules~1{budgetRuleId}"
  /sd/budgetRules:
    $ref: "./sponsored-display.yaml#/paths/~1sd~1budgetRules"
  /sd/adGroups/extended:
    $ref: "./sponsored-display.yaml#/paths/~1sd~1adGroups~1extended"
  /sd/brandSafety/deny:
    $ref: "./sponsored-display.yaml#/paths/~1sd~1brandSafety~1deny"
  /sd/creatives:
    $ref: "./sponsored-display.yaml#/paths/~1sd~1creatives"
  /v2/reports/{reportId}:
    $ref: "./sponsored-display.yaml#/paths/~1v2~1reports~1{reportId}"
  /sd/productAds/extended:
    $ref: "./sponsored-display.yaml#/paths/~1sd~1productAds~1extended"
  /sd/creatives/preview:
    $ref: "./sponsored-display.yaml#/paths/~1sd~1creatives~1preview"
  /sd/negativeTargets:
    $ref: "./sponsored-display.yaml#/paths/~1sd~1negativeTargets"
  /v2/reports/{reportId}/download:
    $ref: "./sponsored-display.yaml#/paths/~1v2~1reports~1{reportId}~1download"
  /sd/negativeTargets/extended:
    $ref: "./sponsored-display.yaml#/paths/~1sd~1negativeTargets~1extended"
  /sd/targets/bid/recommendations:
    $ref: "./sponsored-display.yaml#/paths/~1sd~1targets~1bid~1recommendations"
  /sd/forecasts:
    $ref: "./sponsored-display.yaml#/paths/~1sd~1forecasts"
  /sd/brandSafety/status:
    $ref: "./sponsored-display.yaml#/paths/~1sd~1brandSafety~1status"
  /sd/brandSafety/{requestId}/status:
    $ref: "./sponsored-display.yaml#/paths/~1sd~1brandSafety~1{requestId}~1status"
  /sd/campaigns/budgetRecommendations:
    $ref: "./sponsored-display.yaml#/paths/~1sd~1campaigns~1budgetRecommendations"
  /sd/optimizationRules:
    $ref: "./sponsored-display.yaml#/paths/~1sd~1optimizationRules"
  /sd/negativeTargets/{negativeTargetId}:
    $ref: "./sponsored-display.yaml#/paths/~1sd~1negativeTargets~1{negativeTargetId}"
  /sd/targets/extended/{targetId}:
    $ref: "./sponsored-display.yaml#/paths/~1sd~1targets~1extended~1{targetId}"
  /v2/profiles/{profileId}:
    $ref: "./profiles.yaml#/paths/~1v2~1profiles~1{profileId}"
  /sd/targets:
    $ref: "./sponsored-display.yaml#/paths/~1sd~1targets"
  /sd/campaigns:
    $ref: "./sponsored-display.yaml#/paths/~1sd~1campaigns"
  /sd/snapshots/{snapshotId}/download:
    $ref: "./sponsored-display.yaml#/paths/~1sd~1snapshots~1{snapshotId}~1download"
  /sd/targets/extended:
    $ref: "./sponsored-display.yaml#/paths/~1sd~1targets~1extended"
  /sd/campaigns/extended/{campaignId}:
    $ref: "./sponsored-display.yaml#/paths/~1sd~1campaigns~1extended~1{campaignId}"
  /sd/{recordType}/snapshot:
    $ref: "./sponsored-display.yaml#/paths/~1sd~1{recordType}~1snapshot"
  /sd/targets/{targetId}:
    $ref: "./sponsored-display.yaml#/paths/~1sd~1targets~1{targetId}"
  /sd/campaigns/budget/usage:
    $ref: "./sponsored-display.yaml#/paths/~1sd~1campaigns~1budget~1usage"
info:
  title: "merged spec"
  description: "merged spec"
  version: "1.0.0"
